package com.lottery.biying.util;

import android.content.SharedPreferences;

/**
 * Created by Administrator on 2017/3/30.
 */
public class BundleTag {
    public static final String InviteCode = "InviteCode";
    public static final String PackageName = "PackageName";
    public static final String MultipleMax="MultipleMax";
    public static final String AppendQsMax="AppendQsMax";
    public static final String Information="information";
    public static final String PluginName="minghui";
    public static final int TraceSuccessOrder=786635813;
    public static final String SiteInfo="SiteInfo";
    public static final String Classname="Classname";
    public static final String AuthCode="AuthCode";
    public static final String GroupId="GroupId";
    public static final String Type="Type";
    public static final String Point="Point";
    public static final String DailySalary="DailySalay";
    public static final String StartSalary="StartSalary";
    public static final String BetAmount="BetAmount";
    public static final String Limitedfund="Limitedfund";
    public static final String StartTime="StartTime";
    public static final String EndTime="EndTime";
    public static final String ChangeTempData="ChangeTempData";
    public static final String Incluesubordinate="Incluesubordinate";
    public static final String AccType="AccType";
    public static final String LotteryCode="LotteryCode";
    public static final String Username="Username";
    public static final String Content="Content";
    public static final String MenuName="MenuName";
    public static final String MenuCode="MenuCode";
    public static final String LotteryType="LotteryType";
    public static final String Weishu="ws";
    public static final String Unit="Unit";
    public static final String UnitType="UnitType";
    public static final String LotteryMethod="LotteryMethod";
    public static final String FormatNumber="formatNumber";
    public static final String LotteryName="LotteryName";
    public static final String Times="Times";
    public static final String NumberRecord="NumberRecord";
    public static final String WIN1="WIN1";
    public static final String WIN2="WIN2";
    public static final String WIN3="WIN3";
    public static final String MIN="MIN";
    public static final String MAX="MAX";
    public static final String Winmoney="Winmoney";
    public static final String AWARD="AWARD";
    public static final String HasTrace="HasTrace";
    public static final String BounsType="BounsType";
    public static final String BounsName="BounsName";
    public static final String GameCode="GameCode";
    public static final String NumberList="NumberList";
    public static final String Number="number";
    public static final String BetTimes="BetTimes";
    public static final String BaseUrl="BaseUrl";
    public static final String AndroidKey="AndroidKey";
    public static final String AndroidSecret="AndroidSecret";
    public static final String APP="APP";
    public static final String QQ="QQ";
    public static final String OrderId="orderid";
    public static final String OrderNumber="orderNumber";
    public static final String MotherFucker="MotherFucker";
    public static final String JsonObject = "JsonObject";
    public static final String ChangeState = "ChangeState";
    public static final String Position = "Position";
    public static final int QSTransfer = 1111111;
    public static final String ItemValue = "ItemValue";
    public static final String Weixin = "Weixin";
    public static final String Email = "Email";
    public static final String Phonenum = "Phonenum";
    public static final String Tel = "Tel";
    public static final String level = "level";
    public static final String UserInfo = "UserInfo";
    public static final String BankList = "BankList";
    public static final String URL = "URL";
    public static final String Method = "Method";
    public static final String Platform = "Platform";
    public static final String PlatformName = "PlatformName";
    public static final String Access_token = "Access_token";
    public static final String OrderJson = "OrderJson";
    public static final String Continue = "Continue";
    public static final String FragmentTag = "FragmentTag";
    public static final String UserNameList = "UserNameList";
    public static final int RequestCode = 555;
    public static final int ResultCode = 999;
    public static final int LoginSuccess = 888;
    public static final int ResultCode_Change_Nickname = 9999;
    public static final int ResultCode_Change_QQ = 9996;
    public static final int BandPhone = 9998;
    public static final int CompleteData = 9997;
    public static final String IntentTag = "IntentTag";
    public static final String saoma = "saoma";
    public static final String Data = "Data";
    public static final String Randomtime = "Randomtime";
    public static final String LotteryCategory = "LotteryCategory";
    public static final String title = "title";
    public static final String Timestr = "Timestr";
    public static final String id = "id";
    public static final String type = "type";
    public static final String GameListIndex = "GameListIndex";
    public static final String TitleCode = "TitleCode";
    public static final String Title = "Title";
    public static final String Index = "Index";
    public static final String QS = "QS";
    public static final String List = "list";
    public static final String articleId = "ArticleId";
    public static final String bannerList = "bannerList";    //	首页轮播列表
    public static final String lotteryList = "lotteryList";//彩票首页轮播列表
    public static final String advertList = "advertList";//启动广告图列表
    public static final String logoUrl = "logoUrl";
    public static final String promsList = "promsList";//优惠活动首页轮播列表
    public static final String homeAdvertUrl = "homeAdvertUrl";//首页广告图
    public static final String linkList = "linkList";//备用域名列表
    public static final String ggList = "ggList";//公告列表
    public static final String siteName = "siteName";//网站名称
    public static final String siteFlag = "siteFlag";//网站标识
    public static final String siteDomain = "siteDomain";//线路检测
    public static final String deskTopUrl = "deskTopUrl";//图标地址
    public static final String agentId = "agentId";//代理id
    public static final String chooseBrowser = "chooseBrowser";//浏览器提示
    public static final String isimg = "isimg";//网站标识
  public static final String WebData = "WebData";//网站标识 public static final String Pullstate = "Pullstate";
    public static final String IS_PUSHDFRIST = "true"; // 存储是否第一次进入软件
    public static final String Pullstate = "Pullstate"; // 存储是否第一次进入软件
   public static final String NoticehasClick = "NoticehasClick";//记录首页的公告有没有被点击过
    public static final String BankTransferTypeList="bankTransferTypeList";
    public static final String isShowGame="isShowGame";//	是否显示游戏0不显示 1显示如果为0时，不显示首页的游戏中心和底部菜单。
    public static final String setgesturestate="true";//手势状态是否设置过
    public static final String isopenstate="0";//服务器返回手势状态是否开启
    public static final String isFristsetstate = "true"; // 是否第一次设置手势密码
    public static final String NOT_CountinueMode="NOT_CountinueMode";
    public static final String CountinueMode="CountinueMode";
    public static final String Jumpurl="Jumpurl";
    public static final String IsShowYilou="IsShowYilou";
    public static final String isOpenYaoyiyao="isOpenYaoyiyao";
    public static final String Lottery="Lottery";
    public static final String Desc="desc";
    public static final String Asc="asc";
}